// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ411zRqGaMfEYjnhT5nLSG4K4MMfhzOk',
    appId: '1:295515235862:web:d27dc81b2265244e113737',
    messagingSenderId: '295515235862',
    projectId: 'flutter-push-notificatio-e4c53',
    authDomain: 'flutter-push-notificatio-e4c53.firebaseapp.com',
    storageBucket: 'flutter-push-notificatio-e4c53.firebasestorage.app',
    measurementId: 'G-ERB6DRHGCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE0QZpjfRLWVqjlfpFKF2nqryZdFnc1ls',
    appId: '1:295515235862:android:7e5a9c43d37ba88f113737',
    messagingSenderId: '295515235862',
    projectId: 'flutter-push-notificatio-e4c53',
    storageBucket: 'flutter-push-notificatio-e4c53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHAZo8mNI05_aKQQCGF1tJ5t8QgOV5D-4',
    appId: '1:295515235862:ios:f7ad1b1b8f27b461113737',
    messagingSenderId: '295515235862',
    projectId: 'flutter-push-notificatio-e4c53',
    storageBucket: 'flutter-push-notificatio-e4c53.firebasestorage.app',
    iosBundleId: 'com.example.pushNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHAZo8mNI05_aKQQCGF1tJ5t8QgOV5D-4',
    appId: '1:295515235862:ios:f7ad1b1b8f27b461113737',
    messagingSenderId: '295515235862',
    projectId: 'flutter-push-notificatio-e4c53',
    storageBucket: 'flutter-push-notificatio-e4c53.firebasestorage.app',
    iosBundleId: 'com.example.pushNotifications',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ411zRqGaMfEYjnhT5nLSG4K4MMfhzOk',
    appId: '1:295515235862:web:3dd65facbe7930f8113737',
    messagingSenderId: '295515235862',
    projectId: 'flutter-push-notificatio-e4c53',
    authDomain: 'flutter-push-notificatio-e4c53.firebaseapp.com',
    storageBucket: 'flutter-push-notificatio-e4c53.firebasestorage.app',
    measurementId: 'G-10JCN6FR91',
  );
}
